# SlackPack
# Copyright (C) 2006-2020  Georgi D. Sotirov, gdsotirov@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# DESCRIPTION:
# Local configuration

# You could override any of the following variables by uncommenting it and
# setting the value appropriately

# Database name
#$sp_db   = 'slackpack';

# Database host name
#$sp_host = 'localhost';

# Database port number
#$sp_port = 3306;

# Database local socket location
#$sp_sock = '/var/mysql/mysqld.sock';

# Database user name
#$sp_user = 'slackpack';

# Database user password
#$sp_pass = 'very.secret';

