#!/bin/sh
#
# SlackPack
# Copyright (C) 2010-2019  Georgi D. Sotirov, gdsotirov@gmail.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# DESCRIPTION:
# This is an example script for synchronization with LinuxPackages
# repositories. It uses lftp in reverse mirror mode
#
# REQUIRES:
#  USER and PASS environement variables
#  source directory as parameter
#

TMP=${TMP:-/tmp}

FTPSITE='linuxpackages.net'
FTPUSER=$USER
FTPPASS=$PASS
TARGET="../ftp/pub/Slackware/Slackware-$SOURCE-i386/$FTPUSER"
CMDLOG="$TMP/lp_sync-${SOURCE}-`date +%Y-%m-%d`.log"
OPTS="--reverse --no-recursion --parallel=2 --verbose --log=$CMDLOG"
EXCLUDES="--exclude=openoffice"

if [ "x$1" == "x" ]; then
  echo "usage: $0 version"
  exit 1
fi

# The source directory
SOURCE=$1

if [ ! -x $SOURCE ]; then
  echo "$0: Error: Source '$SOURCE' does not exists!"
  exit 2
fi

echo "lftp -c 'open -e \"mirror $OPTS $EXCLUDES $SOURCE $TARGET\" ftp://${FTPUSER}:${FTPPASS}@${FTPSITE}'"
lftp -c "open -e \"mirror $OPTS $EXCLUDES $SOURCE $TARGET\" ftp://${FTPUSER}:${FTPPASS}@${FTPSITE}"

LFTP_RET=$?

if [ $LFTP_RET -ne 0 ]; then
  echo "$0: Error: lftp returned ${LFTP_RET}. Check log file at '$CMDLOG'."
  exit 3
fi
